defaults:
  quiescence_minutes: 5
  max_commit_interval_minutes: 60
  public_read: true
  git_autosave_enabled: true
  git_autopush: false
  # oauth_providers: [github, google]  # omit to allow all available providers
sites:
  main:
    path: /main
    repo: ''
  sandbox:
    path: /sandbox
    repo: ''
